title: Hubert Lin
email: linhub15@gmail.com
description: |
  Hubert Lin is a web application developer, hobby pc gamer, and competative dancer.
  He enjoys learning about new technologies in his spare time and always looking for problems that need solving.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hubertlin.me" # the base hostname & protocol for your site, e.g. http://example.com
disqus_shortname: "hubertlin"
linkedin_username: linhub15
github_username: linhub15
instagram_username: link_ct


# Build settings
markdown: kramdown
theme: 
plugins:


# Site Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      nav: "site-nav"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "posts"
      nav: "site-nav"
  -
    scope:
      path: "freecodecamp-projects"
    values:
      nav: "fcc-nav"